quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  hibernate-orm:
    database:
      default-schema: happy_takeaway
  flyway:
    schemas:
      - happy_takeaway
    migrate-at-start: true
    baseline-on-migrate: true
  jaeger:
    enabled: true
    agent-host-port: ${JAEGER_HOST:localhost}:${JAEGER_PORT:6831}
    service-name: order-service
    sampler-type: const
    sampler-param: 1
  kubernetes:
    image-pull-policy: IfNotPresent
    env:
      secrets:
        - order-service-db
  container-image:
    build: false
    push: false
    group: happy-takeaway
    registry:
    insecure: true
"%dev":
  quarkus:
    http:
      port: 8087
    grpc:
      server:
        port: 9001
"%test":
  quarkus:
    datasource:
      jdbc:
        driver: org.testcontainers.jdbc.ContainerDatabaseDriver
        url: jdbc:tc:postgresql:12:///