version: '3'

services:
  restaurant-postgres:
    image: debezium/postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-6432}:5432"
    volumes:
      - postgres-data:/data/postgres
volumes:
  postgres-data: