"services":
  "delivery-postgres":
    "environment":
      "POSTGRES_DB": "${POSTGRES_DB}"
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
      "POSTGRES_USER": "${POSTGRES_USERNAME}"
    "image": "debezium/postgres:12-alpine"
    "ports":
      - "6434:5432"
    "volumes":
      - "delivery-db:/data/postgres"
  "order-postgres":
    "environment":
      "POSTGRES_DB": "${POSTGRES_DB}"
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
      "POSTGRES_USER": "${POSTGRES_USERNAME}"
    "image": "debezium/postgres:12-alpine"
    "ports":
      - "6433:5432"
    "volumes":
      - "order-db:/data/postgres"
  "pgadmin":
    "depends_on":
      - "restaurant-postgres"
      - "order-postgres"
      - "delivery-postgres"
    "environment":
      "PGADMIN_DEFAULT_EMAIL": "${PGADMIN_USER}"
      "PGADMIN_DEFAULT_PASSWORD": "${PGADMIN_PASSWORD}"
    "image": "dpage/pgadmin4"
    "ports":
      - "${PGADMIN_PORT:-6555}:80"
    "volumes":
      - "pgadmin:/root/.pgadmin"
      - "./db/postgres-servers.json:/pgadmin4/servers.json"
  "restaurant-postgres":
    "environment":
      "POSTGRES_DB": "${POSTGRES_DB}"
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
      "POSTGRES_USER": "${POSTGRES_USERNAME}"
    "image": "debezium/postgres:12-alpine"
    "ports":
      - "6432:5432"
    "volumes":
      - "restaurant-db:/data/postgres"
"version": "3"
"volumes":
  "delivery-db":
    "driver": "local"
  "order-db":
    "driver": "local"
  "pgadmin":
    "driver": "local"
  "restaurant-db":
    "driver": "local"