apiVersion: v1
kind: Service
metadata:
  name: {{ include "delivery-service.fullname" . }}
  labels:
    {{- include "delivery-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: grpc-server
      port: {{ .Values.service.grpcPort }}
      targetPort: 9000
      protocol: TCP
  selector:
    {{- include "delivery-service.selectorLabels" . | nindent 4 }}
