repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

environments:
  default:
    values:
      - ../../config/default.yaml
  dev:
    values:
      - ../../config/default.yaml
      - ../../config/dev.yaml
  test:
    values:
      - ../../config/default.yaml
      - ../../config/test.yaml
  prod:
    values:
      - ../../config/default.yaml
      - ../../config/prod.yaml

helmDefaults:
  verify: false
  wait: false
  skipDeps: false
  timeout: 600